insert into finanzas_categorias_ingreso ("descripcion") values ('Nómina');
insert into finanzas_categorias_ingreso ("descripcion") values ('Otras ganancias patrimoniales');
insert into finanzas_categorias_ingreso ("descripcion") values ('Ingresos extraordinarios');
insert into finanzas_categorias_ingreso ("descripcion", "cuenta_abono_defecto") select 'Becas', id from finanzas_cuentas where nombre = 'Formación';
insert into finanzas_categorias_ingreso ("descripcion", "cuenta_abono_defecto") select 'Subvenciones', id from finanzas_cuentas where nombre = 'Ahorro';
insert into finanzas_categorias_ingreso ("descripcion", "cuenta_abono_defecto") select 'Devoluciones de Básicos', id from finanzas_cuentas where nombre = 'Básicos';
insert into finanzas_categorias_ingreso ("descripcion", "cuenta_abono_defecto") select 'Devoluciones de Formación', id from finanzas_cuentas where nombre = 'Formación';
insert into finanzas_categorias_ingreso ("descripcion", "cuenta_abono_defecto") select 'Devoluciones de Ocio', id from finanzas_cuentas where nombre = 'Ocio';
insert into finanzas_categorias_ingreso ("descripcion", "cuenta_abono_defecto") select 'Devoluciones de préstamos de otras personas', id from finanzas_cuentas where nombre = 'Básicos';
insert into finanzas_categorias_ingreso ("descripcion", "cuenta_abono_defecto") select 'Dividendos', id from finanzas_cuentas where nombre = 'Bróker Online';
insert into finanzas_categorias_ingreso ("descripcion", "cuenta_abono_defecto") select 'Donación de otras personas', id from finanzas_cuentas where nombre = 'Básicos';
insert into finanzas_categorias_ingreso ("descripcion", "cuenta_abono_defecto") select 'Ganancia en apuestas y juegos', id from finanzas_cuentas where nombre = 'Ocio';
insert into finanzas_categorias_ingreso ("descripcion", "cuenta_abono_defecto") select 'Ingresos por venta de acciones', id from finanzas_cuentas where nombre = 'Bróker Online';
insert into finanzas_categorias_ingreso ("descripcion", "cuenta_abono_defecto") select 'Intereses', id from finanzas_cuentas where nombre = 'Inversión';
insert into finanzas_categorias_ingreso ("descripcion", "cuenta_abono_defecto") select 'Otros', id from finanzas_cuentas where nombre = 'Básicos';
insert into finanzas_categorias_ingreso ("descripcion", "cuenta_abono_defecto") select 'Préstamos de otras personas', id from finanzas_cuentas where nombre = 'Básicos';
insert into finanzas_categorias_ingreso ("descripcion", "cuenta_abono_defecto") select 'Rentas y alquileres', id from finanzas_cuentas where nombre = 'Inversión';
insert into finanzas_categorias_ingreso ("descripcion", "cuenta_abono_defecto") select 'Transferencia a Ahorro', id from finanzas_cuentas where nombre = 'Ahorro';
insert into finanzas_categorias_ingreso ("descripcion", "cuenta_abono_defecto") select 'Transferencia a Básicos', id from finanzas_cuentas where nombre = 'Básicos';
insert into finanzas_categorias_ingreso ("descripcion", "cuenta_abono_defecto") select 'Transferencia a Bróker', id from finanzas_cuentas where nombre = 'Bróker Online';
insert into finanzas_categorias_ingreso ("descripcion", "cuenta_abono_defecto") select 'Transferencia a Formación', id from finanzas_cuentas where nombre = 'Formación';
insert into finanzas_categorias_ingreso ("descripcion", "cuenta_abono_defecto") select 'Transferencia a Inversión', id from finanzas_cuentas where nombre = 'Inversión';
insert into finanzas_categorias_ingreso ("descripcion", "cuenta_abono_defecto") select 'Transferencia a Ocio', id from finanzas_cuentas where nombre = 'Ocio';